optimizer: Adam 
lr: 0.0001
wd: 0.0001
epoch: 300
batch_size: 16
seed: 1234
lr_decay: keras
amsgrad: 1   #for adam optim
save_best_only: 0
make_val_trial: 1
mg: 1
do_lr_decay: 1

#model-related
model:
  margin: 2
  nb_samp: 64600
  first_conv: 128   # no. of filter coefficients 
  in_channels: 1
  filts: [128, [128, 128], [128, 512], [512, 512]]
  blocks: [2, 4]
  nb_fc_node: 1024
  gru_node: 1024
  nb_gru_layer: 3
  nb_classes: 2
  #pre_trn: 1 #flag
  #negative_k: 50




